### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by InitialDW** [form4/form4-auditreport#1]
Hi

Obviously I'm a newbie at this,  I couldn't figure out how to install this module.  What I've done so far

- Run mvn clean install
- Get the form4-auditreport-share-1.0.0.amp
- Run java -jar alfresco-mmt.jar form4-auditreport-share-1.0.0.amp /opt/alfresco/tomcat/webapps/share.war
- Get this upon list command
Module 'form4-auditreport-share' installed in '/opt/alfresco/tomcat/webapps/share.war'
   -    Title:        form4-auditreport-share Share Jar Module
   -    Version:      1.0.0
   -    Install Date: Thu Sep 20 13:27:55 WIB 2018
   -    Description:   Share JAR Module (to be included in the share.war) - SDK 3
- Get this line on my catalina.out (you're not seeing double, I get two lines)
 form4-auditreport-share Share Jar Module, 1.0.0, Share JAR Module (to be included in the share.war) - SDK 3
form4-auditreport-share Share Jar Module, 1.0.0, Share JAR Module (to be included in the share.war) - SDK 3

But still no Audit Trail menu...
Oh, I'm using Community 5.2, anyone?

**Comment by mmrotzek** [comment]
fixed https://github.com/form4/form4-auditreport/commit/e32d4fee252692ae5e5cadaf0a276cb98a90ffd7
